name: FroggyMonitorReward
version: '${project.version}'
main: ru.froggymonitor.rewardplugin.Main
api-version: 1.13
authors: [ FroggyMonitor ]
description: FroggyMonitor plugin that rewards votes and comments
website: https://froggymonitor.ru
softdepend: [ PlaceholderAPI, Vault ]

commands:
  reload:
    description: Перезагрузка плагина
    permission: froggy_monitor_reward.command.reload
permissions:
  froggy_monitor_reward.command.reload:
    default: op