name: FroggyMonitorReward
version: '${project.version}'
main: ru.froggymonitor.rewardplugin.Main
api-version: 1.13
authors: [ FroggyMonitor ]
description: FroggyMonitor plugin that rewards votes and comments
website: https://froggymonitor.ru
softdepend: [ PlaceholderAPI, Vault ]